
image: eclipse-temurin:21-jdk

stages:          
  
  - test
  - deploy



unit-test-job:  
  tags:
    - loadshed1
  stage: test    
  script:
    - ./mvnw test


integration-tests-job:   
  tags:
    - loadshed1
  stage: test   
  script:
    - echo "currently no IT"
 

