_version = 0.1

[oop-ex-toy-robot-group]
activity_id = "oop-ex-toy-robot-group"

[team]
members = [
    "tumog025@student.wethinkcode.co.za",
    "landujhb025@student.wethinkcode.co.za",
    "dahof025@student.wethinkcode.co.za",
    "kemam025@student.wethinkcode.co.za"
]
