robotWorld = "      H   ",\
             "          ",\
             "R         ",\
             " T  T     ",\
             "       R  ",\
             "   H      ",\
             "      M   ",\
             "      T   ",\
             "  R       ",\
             "          "
ShieldMax = 5
port = "2146"
